apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudshop-config
  labels:
    app: cloudshop
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
