apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudshop-frontend
  labels:
    app: cloudshop-frontend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: cloudshop-frontend
  template:
    metadata:
      labels:
        app: cloudshop-frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image.registry }}/{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.resources.frontend | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cloudshop-frontend
  labels:
    app: cloudshop-frontend
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: cloudshop-frontend
  ports:
  - port: {{ .Values.service.frontend.port }}
    targetPort: 80
