apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudshop-worker
  namespace: default
  labels:
    app: cloudshop-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudshop-worker
  template:
    metadata:
      labels:
        app: cloudshop-worker
    spec:
      containers:
      - name: worker
        image: 563955855749.dkr.ecr.ap-south-1.amazonaws.com/cloudshop-worker:latest   # <-- UPDATE to ECR URL after pushing
        imagePullPolicy: Always
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"
